export const barGraphData = {
  d: {
    data: [
      {
        Month: "January",
        "Consumption (kWh)": "1800",
        "Average Temperature ( F)": "41",
        "Avg. Household Consumption (kWh)": "645",
        "Avg. Commercial Consumption (kWh)": "880",
        "Avg. Industrial Consumption (kWh)": "1130",
        "Avg. Residential Consumption (kWh)": "630",
        "Total CO2 Emissions (metric tons)": "1500",
        "Total Revenue from Electricity Sales (USD)": 300000,
        "Total Electricity Generation (GWh)": "2000",
        "": "",
        _1: "",
        color: "#FFD700",
      },
      {
        Month: "February",
        "Consumption (kWh)": "1900",
        "Average Temperature ( F)": "42",
        "Avg. Household Consumption (kWh)": "670",
        "Avg. Commercial Consumption (kWh)": "900",
        "Avg. Industrial Consumption (kWh)": "1150",
        "Avg. Residential Consumption (kWh)": "700",
        "Total CO2 Emissions (metric tons)": "1600",
        "Total Revenue from Electricity Sales (USD)": 310000,
        "Total Electricity Generation (GWh)": "2200",
        "": "",
        _1: "",
        color: "#FF4500",
      },
      {
        Month: "March",
        "Consumption (kWh)": "2100",
        "Average Temperature ( F)": "48",
        "Avg. Household Consumption (kWh)": "700",
        "Avg. Commercial Consumption (kWh)": "920",
        "Avg. Industrial Consumption (kWh)": "1200",
        "Avg. Residential Consumption (kWh)": "720",
        "Total CO2 Emissions (metric tons)": "1700",
        "Total Revenue from Electricity Sales (USD)": 330000,
        "Total Electricity Generation (GWh)": "2300",
        "": "",
        _1: "",
        color: "#800000",
      },
      {
        Month: "April",
        "Consumption (kWh)": "2200",
        "Average Temperature ( F)": "54",
        "Avg. Household Consumption (kWh)": "720",
        "Avg. Commercial Consumption (kWh)": "940",
        "Avg. Industrial Consumption (kWh)": "1220",
        "Avg. Residential Consumption (kWh)": "760",
        "Total CO2 Emissions (metric tons)": "1800",
        "Total Revenue from Electricity Sales (USD)": 350000,
        "Total Electricity Generation (GWh)": "2400",
        "": "",
        _1: "",
        color: "#FF1493",
      },
      {
        Month: "May",
        "Consumption (kWh)": "2000",
        "Average Temperature ( F)": "64",
        "Avg. Household Consumption (kWh)": "680",
        "Avg. Commercial Consumption (kWh)": "900",
        "Avg. Industrial Consumption (kWh)": "1180",
        "Avg. Residential Consumption (kWh)": "720",
        "Total CO2 Emissions (metric tons)": "1600",
        "Total Revenue from Electricity Sales (USD)": 320000,
        "Total Electricity Generation (GWh)": "2100",
        "": "",
        _1: "",
        color: "#6A5ACD",
      },
      {
        Month: "June",
        "Consumption (kWh)": "2300",
        "Average Temperature ( F)": "73",
        "Avg. Household Consumption (kWh)": "740",
        "Avg. Commercial Consumption (kWh)": "980",
        "Avg. Industrial Consumption (kWh)": "1300",
        "Avg. Residential Consumption (kWh)": "720",
        "Total CO2 Emissions (metric tons)": "1900",
        "Total Revenue from Electricity Sales (USD)": 360000,
        "Total Electricity Generation (GWh)": "2500",
        "": "",
        _1: "",
        color: "#2E8B57",
      },
      {
        Month: "July",
        "Consumption (kWh)": "2400",
        "Average Temperature ( F)": "81",
        "Avg. Household Consumption (kWh)": "760",
        "Avg. Commercial Consumption (kWh)": "1000",
        "Avg. Industrial Consumption (kWh)": "1320",
        "Avg. Residential Consumption (kWh)": "720",
        "Total CO2 Emissions (metric tons)": "2000",
        "Total Revenue from Electricity Sales (USD)": 370000,
        "Total Electricity Generation (GWh)": "2600",
        "": "",
        _1: "",
        color: "#FFA07A",
      },
      {
        Month: "August",
        "Consumption (kWh)": "2500",
        "Average Temperature ( F)": "79",
        "Avg. Household Consumption (kWh)": "780",
        "Avg. Commercial Consumption (kWh)": "1020",
        "Avg. Industrial Consumption (kWh)": "1350",
        "Avg. Residential Consumption (kWh)": "730",
        "Total CO2 Emissions (metric tons)": "2100",
        "Total Revenue from Electricity Sales (USD)": 380000,
        "Total Electricity Generation (GWh)": "2700",
        "": "",
        _1: "",
        color: "#1E90FF",
      },
      {
        Month: "September",
        "Consumption (kWh)": "2200",
        "Average Temperature ( F)": "72",
        "Avg. Household Consumption (kWh)": "720",
        "Avg. Commercial Consumption (kWh)": "950",
        "Avg. Industrial Consumption (kWh)": "1250",
        "Avg. Residential Consumption (kWh)": "700",
        "Total CO2 Emissions (metric tons)": "1800",
        "Total Revenue from Electricity Sales (USD)": 350000,
        "Total Electricity Generation (GWh)": "2300",
        "": "",
        _1: "",
        color: "#FF6347",
      },
      {
        Month: "October",
        "Consumption (kWh)": "2000",
        "Average Temperature ( F)": "59",
        "Avg. Household Consumption (kWh)": "680",
        "Avg. Commercial Consumption (kWh)": "900",
        "Avg. Industrial Consumption (kWh)": "1180",
        "Avg. Residential Consumption (kWh)": "720",
        "Total CO2 Emissions (metric tons)": "1600",
        "Total Revenue from Electricity Sales (USD)": 320000,
        "Total Electricity Generation (GWh)": "2100",
        "": "",
        _1: "",
        color: "#4B0082",
      },
      {
        Month: "November",
        "Consumption (kWh)": "1900",
        "Average Temperature ( F)": "50",
        "Avg. Household Consumption (kWh)": "650",
        "Avg. Commercial Consumption (kWh)": "890",
        "Avg. Industrial Consumption (kWh)": "1150",
        "Avg. Residential Consumption (kWh)": "720",
        "Total CO2 Emissions (metric tons)": "1500",
        "Total Revenue from Electricity Sales (USD)": 310000,
        "Total Electricity Generation (GWh)": "2000",
        "": "",
        _1: "",
        color: "#ADFF2F",
      },
      {
        Month: "December",
        "Consumption (kWh)": "1800",
        "Average Temperature ( F)": "43",
        "Avg. Household Consumption (kWh)": "630",
        "Avg. Commercial Consumption (kWh)": "880",
        "Avg. Industrial Consumption (kWh)": "1130",
        "Avg. Residential Consumption (kWh)": "610",
        "Total CO2 Emissions (metric tons)": "1400",
        "Total Revenue from Electricity Sales (USD)": 290000,
        "Total Electricity Generation (GWh)": "1900",
        "": "",
        _1: "",
        color: "#BA55D3",
      },
    ],
  },
};
