export const pieChartData = {
  d: {
    data: [
      {
        name: "Q1",
        "Consumption (kWh)": 25000,
        "Population (millions)": "331",
        "Renewable Energy %": "15%",
        "Total Energy Consumption (GWh)": "8,275",
        "Avg. Household Consumption (kWh)": "756",
        "Avg. Commercial Consumption (kWh)": "1120",
        "Avg. Industrial Consumption (kWh)": "1465",
        "Avg. Residential Consumption (kWh)": "735",
        "Total CO2 Emissions (metric tons)": "30000",
        "Total Revenue from Electricity Sales (USD)": "$87,50,000 ",
        "Total Electricity Generation (GWh)": "10,500",
        color: "#0088FE",
      },
      {
        name: "Q2",
        "Consumption (kWh)": 31000,
        "Population (millions)": "332",
        "Renewable Energy %": "17%",
        "Total Energy Consumption (GWh)": "10,924",
        "Avg. Household Consumption (kWh)": "879",
        "Avg. Commercial Consumption (kWh)": "1243",
        "Avg. Industrial Consumption (kWh)": "1632",
        "Avg. Residential Consumption (kWh)": "849",
        "Total CO2 Emissions (metric tons)": "35000",
        "Total Revenue from Electricity Sales (USD)": "$98,80,000 ",
        "Total Electricity Generation (GWh)": "12,500",
        color: "#00C49F",
      },
      {
        name: "Q3",
        "Consumption (kWh)": 28000,
        "Population (millions)": "333",
        "Renewable Energy %": "16%",
        "Total Energy Consumption (GWh)": "9,288",
        "Avg. Household Consumption (kWh)": "841",
        "Avg. Commercial Consumption (kWh)": "1168",
        "Avg. Industrial Consumption (kWh)": "1565",
        "Avg. Residential Consumption (kWh)": "768",
        "Total CO2 Emissions (metric tons)": "32000",
        "Total Revenue from Electricity Sales (USD)": "$85,00,000 ",
        "Total Electricity Generation (GWh)": "11,200",
        color: "#FFBB28",
      },
      {
        name: "Q4",
        "Consumption (kWh)": 30000,
        "Population (millions)": "334",
        "Renewable Energy %": "18%",
        "Total Energy Consumption (GWh)": "10,020",
        "Avg. Household Consumption (kWh)": "898",
        "Avg. Commercial Consumption (kWh)": "1310",
        "Avg. Industrial Consumption (kWh)": "1432",
        "Avg. Residential Consumption (kWh)": "780",
        "Total CO2 Emissions (metric tons)": "34000",
        "Total Revenue from Electricity Sales (USD)": "$92,50,000 ",
        "Total Electricity Generation (GWh)": "11,800",
        color: "#FF8042",
      },
    ],
  },
};
