export const lineGraphData = {
  d: {
    data: [
      {
        State: "California",
        Abr: "CA",
        "Consumption (kWh)": "15000",
        "Renewable Energy %": 20,
        "Population (millions)": "39",
        "Average Household Size": "3.04",
        "Median Household Income (USD)": "$76,981 ",
        "Avg. Commercial Consumption (kWh)": "3450",
        "Avg. Industrial Consumption (kWh)": "4650",
        "Avg. Residential Consumption (kWh)": "6900",
        "Total CO2 Emissions (metric tons)": "20000",
        "Total Revenue from Electricity Sales (USD)": "$50,00,000 ",
        "Total Electricity Generation (GWh)": "18000",
      },
      {
        State: "Texas",
        Abr: "TX",
        "Consumption (kWh)": "14000",
        "Renewable Energy %": 17,
        "Population (millions)": "29",
        "Average Household Size": "3.12",
        "Median Household Income (USD)": "$64,034 ",
        "Avg. Commercial Consumption (kWh)": "3150",
        "Avg. Industrial Consumption (kWh)": "4200",
        "Avg. Residential Consumption (kWh)": "6650",
        "Total CO2 Emissions (metric tons)": "18500",
        "Total Revenue from Electricity Sales (USD)": "$47,50,000 ",
        "Total Electricity Generation (GWh)": "17000",
      },
      {
        State: "Florida",
        Abr: "FL",
        "Consumption (kWh)": "13000",
        "Renewable Energy %": 13,
        "Population (millions)": "21",
        "Average Household Size": "2.65",
        "Median Household Income (USD)": "$59,227 ",
        "Avg. Commercial Consumption (kWh)": "2950",
        "Avg. Industrial Consumption (kWh)": "3900",
        "Avg. Residential Consumption (kWh)": "6150",
        "Total CO2 Emissions (metric tons)": "18000",
        "Total Revenue from Electricity Sales (USD)": "$45,00,000 ",
        "Total Electricity Generation (GWh)": "16000",
      },
      {
        State: "New York",
        Abr: "NY",
        "Consumption (kWh)": "12000",
        "Renewable Energy %": 15,
        "Population (millions)": "20",
        "Average Household Size": "2.63",
        "Median Household Income (USD)": "$72,108 ",
        "Avg. Commercial Consumption (kWh)": "2700",
        "Avg. Industrial Consumption (kWh)": "3600",
        "Avg. Residential Consumption (kWh)": "5700",
        "Total CO2 Emissions (metric tons)": "17500",
        "Total Revenue from Electricity Sales (USD)": "$42,50,000 ",
        "Total Electricity Generation (GWh)": "15000",
      },
      {
        State: "Illinois",
        Abr: "IL",
        "Consumption (kWh)": "11000",
        "Renewable Energy %": 12,
        "Population (millions)": "13",
        "Average Household Size": "2.51",
        "Median Household Income (USD)": "$65,030 ",
        "Avg. Commercial Consumption (kWh)": "2500",
        "Avg. Industrial Consumption (kWh)": "3300",
        "Avg. Residential Consumption (kWh)": "5200",
        "Total CO2 Emissions (metric tons)": "17000",
        "Total Revenue from Electricity Sales (USD)": "$40,00,000 ",
        "Total Electricity Generation (GWh)": "14000",
      },
      {
        State: "Pennsylvania",
        Abr: "PA",
        "Consumption (kWh)": "10000",
        "Renewable Energy %": 14,
        "Population (millions)": "12",
        "Average Household Size": "2.48",
        "Median Household Income (USD)": "$61,868 ",
        "Avg. Commercial Consumption (kWh)": "2300",
        "Avg. Industrial Consumption (kWh)": "3100",
        "Avg. Residential Consumption (kWh)": "4700",
        "Total CO2 Emissions (metric tons)": "16000",
        "Total Revenue from Electricity Sales (USD)": "$37,50,000 ",
        "Total Electricity Generation (GWh)": "13000",
      },
      {
        State: "Ohio",
        Abr: "OH",
        "Consumption (kWh)": "9500",
        "Renewable Energy %": 16,
        "Population (millions)": "12",
        "Average Household Size": "2.47",
        "Median Household Income (USD)": "$60,876 ",
        "Avg. Commercial Consumption (kWh)": "2100",
        "Avg. Industrial Consumption (kWh)": "2900",
        "Avg. Residential Consumption (kWh)": "4500",
        "Total CO2 Emissions (metric tons)": "15500",
        "Total Revenue from Electricity Sales (USD)": "$35,00,000 ",
        "Total Electricity Generation (GWh)": "12000",
      },
      {
        State: "Georgia",
        Abr: "GA",
        "Consumption (kWh)": "9000",
        "Renewable Energy %": 11,
        "Population (millions)": "11",
        "Average Household Size": "2.75",
        "Median Household Income (USD)": "$57,418 ",
        "Avg. Commercial Consumption (kWh)": "1900",
        "Avg. Industrial Consumption (kWh)": "2700",
        "Avg. Residential Consumption (kWh)": "4400",
        "Total CO2 Emissions (metric tons)": "15000",
        "Total Revenue from Electricity Sales (USD)": "$32,50,000 ",
        "Total Electricity Generation (GWh)": "11000",
      },
      {
        State: "Michigan",
        Abr: "MI",
        "Consumption (kWh)": "8500",
        "Renewable Energy %": 10,
        "Population (millions)": "10",
        "Average Household Size": "2.44",
        "Median Household Income (USD)": "$57,144 ",
        "Avg. Commercial Consumption (kWh)": "1700",
        "Avg. Industrial Consumption (kWh)": "2500",
        "Avg. Residential Consumption (kWh)": "4300",
        "Total CO2 Emissions (metric tons)": "14500",
        "Total Revenue from Electricity Sales (USD)": "$30,00,000 ",
        "Total Electricity Generation (GWh)": "10500",
      },
      {
        State: "North Carolina",
        Abr: "NC",
        "Consumption (kWh)": "8000",
        "Renewable Energy %": 13,
        "Population (millions)": "10",
        "Average Household Size": "2.54",
        "Median Household Income (USD)": "$53,855 ",
        "Avg. Commercial Consumption (kWh)": "1500",
        "Avg. Industrial Consumption (kWh)": "2300",
        "Avg. Residential Consumption (kWh)": "4200",
        "Total CO2 Emissions (metric tons)": "14000",
        "Total Revenue from Electricity Sales (USD)": "$27,50,000 ",
        "Total Electricity Generation (GWh)": "10000",
      },
      {
        State: "New Jersey",
        Abr: "NJ",
        "Consumption (kWh)": "7500",
        "Renewable Energy %": 18,
        "Population (millions)": "9",
        "Average Household Size": "2.64",
        "Median Household Income (USD)": "$75,176 ",
        "Avg. Commercial Consumption (kWh)": "1300",
        "Avg. Industrial Consumption (kWh)": "2100",
        "Avg. Residential Consumption (kWh)": "4100",
        "Total CO2 Emissions (metric tons)": "13500",
        "Total Revenue from Electricity Sales (USD)": "$25,00,000 ",
        "Total Electricity Generation (GWh)": "9500",
      },
      {
        State: "Virginia",
        Abr: "VA",
        "Consumption (kWh)": "7000",
        "Renewable Energy %": 17,
        "Population (millions)": "8",
        "Average Household Size": "2.54",
        "Median Household Income (USD)": "$74,222 ",
        "Avg. Commercial Consumption (kWh)": "1100",
        "Avg. Industrial Consumption (kWh)": "1900",
        "Avg. Residential Consumption (kWh)": "4000",
        "Total CO2 Emissions (metric tons)": "13000",
        "Total Revenue from Electricity Sales (USD)": "$22,50,000 ",
        "Total Electricity Generation (GWh)": "9000",
      },
      {
        State: "Washington",
        Abr: "WA",
        "Consumption (kWh)": "6500",
        "Renewable Energy %": 21,
        "Population (millions)": "7",
        "Average Household Size": "2.53",
        "Median Household Income (USD)": "$74,073 ",
        "Avg. Commercial Consumption (kWh)": "900",
        "Avg. Industrial Consumption (kWh)": "1700",
        "Avg. Residential Consumption (kWh)": "3800",
        "Total CO2 Emissions (metric tons)": "12500",
        "Total Revenue from Electricity Sales (USD)": "$20,00,000 ",
        "Total Electricity Generation (GWh)": "8500",
      },
      {
        State: "Arizona",
        Abr: "AZ",
        "Consumption (kWh)": "6000",
        "Renewable Energy %": 19,
        "Population (millions)": "7",
        "Average Household Size": "2.61",
        "Median Household Income (USD)": "$61,125 ",
        "Avg. Commercial Consumption (kWh)": "700",
        "Avg. Industrial Consumption (kWh)": "1500",
        "Avg. Residential Consumption (kWh)": "3800",
        "Total CO2 Emissions (metric tons)": "12000",
        "Total Revenue from Electricity Sales (USD)": "$17,50,000 ",
        "Total Electricity Generation (GWh)": "8000",
      },
      {
        State: "Massachusetts",
        Abr: "MA",
        "Consumption (kWh)": "5500",
        "Renewable Energy %": 22,
        "Population (millions)": "7",
        "Average Household Size": "2.53",
        "Median Household Income (USD)": "$77,385 ",
        "Avg. Commercial Consumption (kWh)": "500",
        "Avg. Industrial Consumption (kWh)": "1300",
        "Avg. Residential Consumption (kWh)": "3700",
        "Total CO2 Emissions (metric tons)": "11500",
        "Total Revenue from Electricity Sales (USD)": "$15,00,000 ",
        "Total Electricity Generation (GWh)": "7500",
      },
      {
        State: "Tennessee",
        Abr: "TN",
        "Consumption (kWh)": "5000",
        "Renewable Energy %": 9,
        "Population (millions)": "6",
        "Average Household Size": "2.57",
        "Median Household Income (USD)": "$56,071 ",
        "Avg. Commercial Consumption (kWh)": "300",
        "Avg. Industrial Consumption (kWh)": "1100",
        "Avg. Residential Consumption (kWh)": "3600",
        "Total CO2 Emissions (metric tons)": "11000",
        "Total Revenue from Electricity Sales (USD)": "$12,50,000 ",
        "Total Electricity Generation (GWh)": "7000",
      },
      {
        State: "Indiana",
        Abr: "IN",
        "Consumption (kWh)": "4500",
        "Renewable Energy %": 11,
        "Population (millions)": "6",
        "Average Household Size": "2.5",
        "Median Household Income (USD)": "$57,603 ",
        "Avg. Commercial Consumption (kWh)": "100",
        "Avg. Industrial Consumption (kWh)": "900",
        "Avg. Residential Consumption (kWh)": "3500",
        "Total CO2 Emissions (metric tons)": "10500",
        "Total Revenue from Electricity Sales (USD)": "$10,00,000 ",
        "Total Electricity Generation (GWh)": "6500",
      },
      {
        State: "Missouri",
        Abr: "MO",
        "Consumption (kWh)": "4000",
        "Renewable Energy %": 8,
        "Population (millions)": "6",
        "Average Household Size": "2.45",
        "Median Household Income (USD)": "$56,422 ",
        "Avg. Commercial Consumption (kWh)": "200",
        "Avg. Industrial Consumption (kWh)": "700",
        "Avg. Residential Consumption (kWh)": "3100",
        "Total CO2 Emissions (metric tons)": "10000",
        "Total Revenue from Electricity Sales (USD)": "$7,50,000 ",
        "Total Electricity Generation (GWh)": "6000",
      },
      {
        State: "Maryland",
        Abr: "MD",
        "Consumption (kWh)": "3500",
        "Renewable Energy %": 12,
        "Population (millions)": "6",
        "Average Household Size": "2.68",
        "Median Household Income (USD)": "$81,868 ",
        "Avg. Commercial Consumption (kWh)": "400",
        "Avg. Industrial Consumption (kWh)": "500",
        "Avg. Residential Consumption (kWh)": "2600",
        "Total CO2 Emissions (metric tons)": "9500",
        "Total Revenue from Electricity Sales (USD)": "$5,00,000 ",
        "Total Electricity Generation (GWh)": "5500",
      },
      {
        State: "Wisconsin",
        Abr: "WI",
        "Consumption (kWh)": "3000",
        "Renewable Energy %": 10,
        "Population (millions)": "5",
        "Average Household Size": "2.49",
        "Median Household Income (USD)": "$64,168 ",
        "Avg. Commercial Consumption (kWh)": "300",
        "Avg. Industrial Consumption (kWh)": "400",
        "Avg. Residential Consumption (kWh)": "2300",
        "Total CO2 Emissions (metric tons)": "9000",
        "Total Revenue from Electricity Sales (USD)": "$2,50,000 ",
        "Total Electricity Generation (GWh)": "5000",
      },
    ],
  },
};
